spring:
  kafka:
    bootstrap-servers: localhost:29092, localhost:39092
    producer:
      properties:
        "[max.block.ms]": "10000"
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
management:
  endpoint:
    health:
      show-components: always
  health:
    diskspace:
      enabled: false
    ping:
      enabled: false
downstreams:
  kafka:
    topics:
      bookmark: "bookmarks-producer"
      health: "health-indicator"

